lugares = ["La_Alhambra", "Machu_Picchu","Taj_Mahal","Coliseo_Romano", "Tucuman"]
print("lista normal")
print(lugares)
print("lista con sorted()")
print(sorted(lugares))
print("lista normal")
print(lugares)
print("lista con sorted() y reversa")
print(sorted(lugares,reverse=True))
print("lista normal")
print(lugares)
print("lista en reversa")
lugares.reverse()
print(lugares)
print("lista normal")
lugares.reverse()
print(lugares)
print("lista con sort")
lugares.sort()
print(lugares)
print("lista con sort inverso")
lugares.sort(reverse=True)
print(lugares)